package Modelos;
// Generated 18-nov-2020 15:45:27 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Comparator;

/**
 * FacturasLin generated by hbm2java
 */
public class FacturasLin  implements java.io.Serializable {


     private FacturasLinId id;
     private Articulos articulos;
     private FacturasCab facturasCab;
     private BigDecimal cantidad;
     private BigDecimal precio;
     private BigDecimal dtolinea;
     private BigDecimal ivalinea;

    public FacturasLin() {
    }

    public FacturasLin(FacturasLinId id, Articulos articulos, FacturasCab facturasCab, BigDecimal cantidad, BigDecimal precio, BigDecimal dtolinea, BigDecimal ivalinea) {
       this.id = id;
       this.articulos = articulos;
       this.facturasCab = facturasCab;
       this.cantidad = cantidad;
       this.precio = precio;
       this.dtolinea = dtolinea;
       this.ivalinea = ivalinea;
    }
   
    public FacturasLinId getId() {
        return this.id;
    }
    
    public void setId(FacturasLinId id) {
        this.id = id;
    }
    public Articulos getArticulos() {
        return this.articulos;
    }
    
    public void setArticulos(Articulos articulos) {
        this.articulos = articulos;
    }
    public FacturasCab getFacturasCab() {
        return this.facturasCab;
    }
    
    public void setFacturasCab(FacturasCab facturasCab) {
        this.facturasCab = facturasCab;
    }
    public BigDecimal getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(BigDecimal cantidad) {
        this.cantidad = cantidad;
    }
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }
    public BigDecimal getDtolinea() {
        return this.dtolinea;
    }
    
    public void setDtolinea(BigDecimal dtolinea) {
        this.dtolinea = dtolinea;
    }
    public BigDecimal getIvalinea() {
        return this.ivalinea;
    }
    
    public void setIvalinea(BigDecimal ivalinea) {
        this.ivalinea = ivalinea;
    }
    public BigDecimal calcularSubtotal(){
        BigDecimal subtotal;
        subtotal=this.precio.multiply(this.cantidad);
        return subtotal;
    }
    public BigDecimal calcularDescuentoLinea(){
        BigDecimal descuento,subtotal;
        subtotal=calcularSubtotal();
        descuento=subtotal.multiply(this.dtolinea);
        descuento=descuento.divide(new BigDecimal("100"));
        return descuento;
        
        
    }
    public BigDecimal calcularIva(){
        BigDecimal iva,subtotal,descuento;
        subtotal=calcularSubtotal();
        descuento=calcularDescuentoLinea();
        iva=subtotal.subtract(descuento);
        iva=iva.multiply(this.ivalinea);
        iva=iva.divide(new BigDecimal("100"));
        return iva;
        
    }
    
    public static Comparator<FacturasLin> ordenarLineaFactura = new Comparator<FacturasLin>() {
        

         @Override
         public int compare(FacturasLin o1, FacturasLin o2) {
             long nLinea1=o1.getId().getLineafac();
             long nLinea2=o2.getId().getLineafac();
             
            return (int) nLinea1-(int)nLinea2;
         }

    };



}


